---
- name: Ensure nginx is installed
  apk:
    name: nginx

- name: Ensure nginx is configured to service simple files
  copy:
    src: files/default.conf
    dest: /etc/nginx/http.d/default.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure there is an index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/localhost/htdocs/index.html
    owner: nginx
    group: www-data
    mode: '0644'
    
- name: Ensure nginx is restarted
  service:
    name: nginx
    state: restarted    